name = "dummy"
token = "CHANGE_ME"
players = 4
debug = true

host = "0.0.0.0"
port = 7788

# put the server on the master list
announce = false
password = "PASSWORD"

description = "example"
gamemode = "rp"
language = "en"
website = "example.com"

modules = ["js-module"]
resources = ["scripts/*"]
